# Generated by Django 3.2.8 on 2021-10-06 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_mileage_service_mileage_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='type',
            new_name='service_type',
        ),
    ]
