# Generated by Django 3.2.8 on 2021-10-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
