# Generated by Django 3.2.8 on 2021-10-06 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_image',
        ),
    ]
